import { Navbar } from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Head from "next/head";
import { Toaster } from "@/components/ui/toaster";
import Loader from "@/components/Loader/Loader";
const inter = Rubik({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Anizavr",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ru">
            <head>
                <link
                    rel="shortcut icon"
                    href="/favicon/favicon.ico"
                    sizes="any"
                />
            </head>
            <body className={inter.className}>
                <main>
                    <Navbar />
                    <div className="max-w-[1920px] mx-auto">
                        {children}
                    </div>
                </main>
                <Toaster />
            </body>
        </html>
    );
}
