"use client";
import { Navbar } from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Anizavr",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ru">
            <Head>
                <link
                    rel="shortcut icon"
                    href="/favicon.ico"
                    type="image/x-icon"
                />
            </Head>
            <body className={inter.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
